version = 3.11.1
runner.dialect = scala3

# A polished Scala 3 profile:
# - stable, widely used defaults
# - vertical alignment for readable declarations and matches
# - compact but not cramped line length
preset = defaultWithAlign
maxColumn = 100

indent.main = 2
indent.callSite = 2
indent.defnSite = 4
indent.ctorSite = 4

docstrings.style = Asterisk

newlines.source = keep
newlines.topLevelStatementBlankLines = [
  {
    blanks = 1
  }
]
newlines.beforeMultiline = fold
newlines.afterCurlyLambdaParams = squash

danglingParentheses.preset = true

rewrite.rules = [
  Imports
]

rewrite.imports.sort = scalastyle

newlines.selectChains.classicCanStartWithBraceApply = false
assumeStandardLibraryStripMargin = true
