apiVersion: initkit.io/v1alpha1
kind: WorkstationProfile

metadata:
  name: fedora-dev
  labels:
    distro: fedora

spec:
  target:
    os:
      family: linux
      distribution: fedora
      architecture: amd64

  policy:
    dryRun: false
    continueOnError: false
    requireSudo: true
    reboot:
      allowed: false
      prompt: true

  vars:
    home: "${HOME}"
    user: "${USER}"
    binDir: "${HOME}/.local/bin"
    stateFile: "${HOME}/.local/state/initkit/fedora-dev.state.json"

  sources:
    dnf:
      repositories:
        - name: vscode
          description: Visual Studio Code
          baseUrl: https://packages.microsoft.com/yumrepos/vscode
          gpgKey: https://packages.microsoft.com/keys/microsoft.asc
    flatpak:
      remotes:
        - name: flathub
          url: https://flathub.org/repo/flathub.flatpakrepo
          ifMissing: true

  plan:
    - name: fedora-base-cli
      kind: dnf-packages
      description: Build tools and terminal basics.
      execution:
        mode: sequential
        locks: [system-package-manager]
      when:
        os:
          family: linux
          distribution:
            oneOf: [fedora, rhel, centos]
      spec:
        install:
          - "@development-tools"
          - ca-certificates
          - curl
          - git
          - gnupg2
          - jq
          - unzip
          - zsh

    - name: fedora-containers
      kind: dnf-packages
      description: Container tools from Fedora repos.
      execution:
        mode: sequential
        locks: [system-package-manager]
      when:
        os:
          family: linux
          distribution:
            oneOf: [fedora, rhel, centos]
      spec:
        install:
          - podman
          - buildah
          - skopeo
          - docker-compose

    - name: fedora-flatpaks
      kind: flatpak-packages
      description: Desktop apps through Flathub.
      execution:
        mode: sequential
        locks: [desktop-package-manager]
      spec:
        remote: flathub
        system: true
        install:
          - org.mozilla.firefox
          - com.slack.Slack

    - name: local-bin
      kind: commands
      description: Make sure user-local bin exists.
      spec:
        items:
          - name: ensure-local-bin
            run: "mkdir -p ${binDir}"
            sudo: false
